# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-04 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheather', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('images', models.FileField(upload_to='train/')),
                ('state', models.CharField(max_length=200)),
                ('distric', models.CharField(max_length=200)),
                ('usid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
