# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_upload_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wetr', models.CharField(max_length=200)),
                ('are', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('traf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Upload_Model')),
            ],
        ),
    ]
